config/routes.rb
Rails.application.routes.draw do
  resources :beacons
  resources :functions
  resources :semaforos
  resources :mac_addresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beacon.rb
class Beacon < ApplicationRecord
  belongs_to :function
  has_one :semaforo
  has_many :dispositivos

  validates :nombre, uniqueness: true
end

app/models/dispositivo.rb
class Dispositivo < ApplicationRecord
  belongs_to :beacon

  validates :mac_address, uniqueness: true

  def paso_un_tiempo?
    ultima_conexion < 5.seconds.ago
  end

  def actualizar_ultima_conexion!
    update(ultima_conexion: Time.now) if paso_un_tiempo?
  end
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  has_many :beacons

  validates :nombre, uniqueness: true
end

app/models/function.rb
class Function < ApplicationRecord
  has_many :beacons

  validates :nombre, uniqueness: true
end

app/models/semaforo.rb
class Semaforo < ApplicationRecord
  belongs_to :beacon

  enum estado: [ :rojo, :amarillo, :verde ]

  def cambiar_estado
    case estado
      when "rojo"
        "amarillo"
      when "amarillo"
        "verde"
      when "verde"
        "rojo"
      else
        "rojo"
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  #before_action :set_beacon, only: [ :show, :edit, :update, :destroy ]
  before_action :set_beacon, only: [ :edit, :update, :destroy ]

  def show
    @beacon = Beacon.find_by(nombre: params[:id]) || Beacon.find(params[:id])

    if params[:mac_address].present?

      if @dispositivo = Dispositivo.find_by(mac_address: params[:mac_address])
        @dispositivo.actualizar_ultima_conexion!
      else
        Dispositivo.create(mac_address: params[:mac_address],
                           beacon: @beacon,
                           ultima_conexion: Time.now)
      end

    end

    respond_to do |format|
      format.html
      format.json { render json: @beacon }
    end
  end

  def index
    @beacons = Beacon.all
  end

  def new
    @beacon = Beacon.new
  end

  def create
    @beacon = Beacon.new(beacon_params)

    if @beacon.save
      redirect_to @beacon
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @beacon.update(beacon_params)
      redirect_to @beacon
    else
      render 'edit'
    end
  end

  def destroy
    @beacon.destroy

    redirect_to beacons_path
  end

  private

    def beacon_params
      params.require(:beacon).permit(:uuid, :latitud, :longitud, :function_id, :nombre, :nombre_largo)
    end

    def set_beacon
      @beacon = Beacon.find(params[:id])
    end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: [ :show, :edit, :update, :destroy ]

  def show
    respond_to do |format|
      format.html
      format.json { render json: @function }
    end
  end

  def index
    @functions = Function.all
  end

  def new
    @function = Function.new
  end

  def create
    @function = Function.new(function_params)

    if @function.save
      redirect_to @function
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @function.update(function_params)
      redirect_to @function
    else
      render 'edit'
    end
  end

  def destroy
    @function.destroy

    redirect_to functiones_path
  end

  private

    def function_params
      params.require(:function).permit(:nombre)
    end

    def set_function
      @function = Function.find(params[:id])
    end
end

app/controllers/semaforos_controller.rb
class SemaforosController < ApplicationController
  before_action :set_semaforo, only: [ :show, :edit, :update, :destroy ]

  def show
    nuevo_estado = @semaforo.cambiar_estado
    @semaforo.update(estado: nuevo_estado)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @semaforo }
    end
  end

  def index
    @semaforos = Semaforo.all
  end

  def new
    @semaforo = Semaforo.new
  end

  def create
    @semaforo = Semaforo.new(semaforo_params)

    if @semaforo.save
      redirect_to @semaforo
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @semaforo.update(semaforo_params)
      redirect_to @semaforo
    else
      render 'new'
    end
  end

  def destroy
    @semaforo.destroy

    redirect_to semaforos_path
  end

  private

    def semaforo_params
      params.require(:semaforo).permit(:beacon_id)
    end

    def set_semaforo
      @semaforo = Semaforo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/funciones_helper.rb
module FuncionesHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/mac_addresses_helper.rb
module MacAddressesHelper
end

app/helpers/semaforos_helper.rb
module SemaforosHelper
end

app/views/beacons/_form.html.erb
<%= simple_form_for @beacon do |f| %>
  <%= f.input :uuid %>
  <%= f.input :latitud %>
  <%= f.input :longitud %>
  <%= f.input :nombre %>
  <%= f.input :nombre_largo %>
  <%= f.association :function, label_method: :nombre, value_method: :id, include_blank: false %>

  <%= f.button :submit %>
<% end %>

app/views/beacons/edit.html.erb
<h1>Beacons#edit</h1>

<%= render 'form' %>

app/views/beacons/index.html.erb
<h1>Beacons#index</h1>

<%= link_to 'Crear Beacon', new_beacon_path %>

<table class="table">

  <thead>
    <tr>
      <th>UUID</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Nombre</th>
      <th>Nombre largo</th>
      <th>Visitas</th>
      <th>Función</th>
      <th colspan="4">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.uuid %></td>
        <td><%= beacon.latitud %></td>
        <td><%= beacon.longitud %></td>
        <td><%= beacon.nombre %></td>
        <td><%= beacon.nombre_largo %></td>
        <td><%= beacon.dispositivos.count %></td>
        <td><%= beacon.function.nombre %></td>

        <td><%= link_to "Mapa", "https://www.google.com.ar/maps/dir//#{beacon.latitud},#{beacon.longitud}/" %></td>
        <td><%= link_to "Ver", beacon %></td>
        <td><%= link_to "Editar", edit_beacon_path(beacon) %></td>
        <td><%= link_to "Eliminar", beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/beacons/new.html.erb
<h1>Beacons#new</h1>

<%= render 'form' %>

app/views/beacons/show.html.erb
<h1>Beacons#show</h1>

<h2>UUID</h2>
<%= @beacon.uuid %>

<h2>Latitud</h2>
<%= @beacon.latitud %>

<h2>Longitud</h2>
<%= @beacon.longitud %>

<h2>Nombre</h2>
<%= @beacon.nombre %>

<h2>Nombre largo</h2>
<%= @beacon.nombre_largo %>

<h2>Visitas</h2>
<%= @beacon.dispositivos.count %>

<h2>Funcion</h2>
<%= @beacon.function.nombre %>

app/views/functions/_form.html.erb
<%= simple_form_for @function do |f| %>
  <%= f.input :nombre %>

  <%= f.button :submit %>
<% end %>

app/views/functions/edit.html.erb
<h1>Functions#edit</h1>

<%= render 'form' %>

app/views/functions/index.html.erb
<h1>Functions#index</h1>

<%= link_to 'Crear Function', new_function_path %>

<table class="table">

  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th colspan="3">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @functions.each do |function| %>
      <tr>
        <td><%= function.id %></td>
        <td><%= function.nombre %></td>

        <td><%= link_to "Ver", function %></td>
        <td><%= link_to "Editar", edit_function_path(function) %></td>
        <td><%= link_to "Eliminar", function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/functions/new.html.erb
<h1>Functions#new</h1>

<%= render 'form' %>

app/views/functions/show.html.erb
<h1>Functions#show</h1>

<h2>ID</h2>
<%= @function.id %>

<h2>Nombre</h2>
<%= @function.nombre %>

<h2>Beacons</h2>

  <% if @function.beacons.count == 0 %>
    <h4>No hay beacons asignados a esta función.</h4>
  <% else %>
    <table>

      <thead>
        <tr>
          <th>UUID</th>
          <th>Latitud</th>
          <th>Longitud</th>
        </tr>
      </thead>

      <tbody>
        <% @function.beacons.each do |beacon| %>
          <tr>
            <td><%= beacon.uuid %></td>
            <td><%= beacon.latitud %></td>
            <td><%= beacon.longitud %></td>
            <td><%= beacon.nombre %></td>
            <td><%= beacon.function.nombre %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taller2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>


    <br>
    <br>
    <%= link_to 'Beacons#index', beacons_path %> |
    <%= link_to 'Funciones#index', functions_path %> |
    <%= link_to 'Semaforos#index', semaforos_path %>

  </body>
</html>

app/views/semaforos/_form.html.erb
<%= simple_form_for @semaforo do |f| %>
  <%= f.association :beacon, label_method: :nombre, value_method: :id, include_blank: false %>

  <%= f.button :submit %>
<% end %>

app/views/semaforos/edit.html.erb
<h1>Semaforos#edit</h1>

<%= render 'form' %>

app/views/semaforos/index.html.erb
<h1>Semaforos#index</h1>

<%= link_to 'Crear Semaforo', new_semaforo_path %>

<table class="table">

  <thead>
    <tr>
      <th>ID</th>
      <th>ID-Beacon</th>
      <th>Estado</th>
      <th colspan="3">Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @semaforos.each do |semaforo| %>
      <tr>
        <td><%= semaforo.id %></td>
        <td><%= semaforo.beacon.id %></td>
        <td><%= semaforo.estado %></td>

        <td><%= link_to "Ver", semaforo %></td>
        <td><%= link_to "Editar", edit_semaforo_path(semaforo) %></td>
        <td><%= link_to "Eliminar", semaforo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/semaforos/new.html.erb
<h1>Semaforos#new</h1>

<%= render 'form' %>

app/views/semaforos/show.html.erb
<script type="text/javascript">
$(document).ready(function() {
  setTimeout(function() {
    window.location.reload();
  }, 3000);
});
</script>

<h1>Semaforo#show</h1>

<h2>Color</h2>
<%= @semaforo.estado %>